// frontend/src/components/AuthModal.vue
<template>
  <TransitionRoot as="template" :show="open">
    <Dialog class="relative z-50" @close="$emit('close')">
      <TransitionChild
        as="template"
        enter="ease-out duration-300"
        enter-from="opacity-0"
        enter-to="opacity-100"
        leave="ease-in duration-200"
        leave-from="opacity-100"
        leave-to="opacity-0"
      >
        <div class="fixed inset-0 bg-black/20 backdrop-blur-md transition-opacity" />
      </TransitionChild>

      <div class="fixed inset-0 z-10 w-screen overflow-y-auto">
        <div class="flex min-h-full items-end justify-center p-4 text-center sm:items-center sm:p-0">
          <TransitionChild
            as="template"
            enter="ease-out duration-300"
            enter-from="opacity-0 translate-y-4 sm:translate-y-0 sm:scale-95"
            enter-to="opacity-100 translate-y-0 sm:scale-100"
            leave="ease-in duration-200"
            leave-from="opacity-100 translate-y-0 sm:scale-100"
            leave-to="opacity-0 translate-y-4 sm:translate-y-0 sm:scale-95"
          >
            <DialogPanel class="relative transform overflow-hidden bg-gray-900 px-4 pb-4 pt-5 text-left shadow-xl transition-all sm:my-8 sm:w-full sm:max-w-lg sm:p-0">
              <!-- Close button -->
              <div class="absolute right-0 top-0 pr-4 pt-4">
                <button
                  type="button"
                  class="rounded-md bg-gray-900 text-gray-400 hover:text-white focus:outline-none focus:ring-2 focus:ring-indigo-500"
                  @click="$emit('close')"
                >
                  <span class="sr-only">Close</span>
                  <XMarkIcon class="h-6 w-6" aria-hidden="true" />
                </button>
              </div>

              <!-- Login form content -->
              <div class="flex min-h-full flex-1 flex-col justify-center py-12 sm:px-6 lg:px-8">
                <div class="sm:mx-auto sm:w-full sm:max-w-md">
                  <div class="h-10 w-auto text-indigo-400 font-bold text-2xl text-center">
                    LinkShort
                  </div>
                  <h2 class="mt-6 text-center text-2xl/9 font-bold tracking-tight text-white">
                    Sign in to your account
                  </h2>
                </div>

                <div class="mt-10 sm:mx-auto sm:w-full sm:max-w-[480px]">
                  <div class="bg-gray-800/50 px-6 py-12 outline -outline-offset-1 outline-white/10 sm:rounded-lg sm:px-12">
                    <form class="space-y-6" @submit.prevent="handleSubmit">
                      <div>
                        <label for="email" class="block text-sm/6 font-medium text-white">
                          Email address
                        </label>
                        <div class="mt-2">
                          <input
                            id="email"
                            v-model="email"
                            type="email"
                            name="email"
                            autocomplete="email"
                            required
                            class="block w-full rounded-md bg-white/5 px-3 py-1.5 text-base text-white outline-1 -outline-offset-1 outline-white/10 placeholder:text-gray-500 focus:outline-2 focus:-outline-offset-2 focus:outline-indigo-500 sm:text-sm/6"
                          />
                        </div>
                      </div>

                      <div>
                        <label for="password" class="block text-sm/6 font-medium text-white">
                          Password
                        </label>
                        <div class="mt-2">
                          <input
                            id="password"
                            v-model="password"
                            type="password"
                            name="password"
                            autocomplete="current-password"
                            required
                            class="block w-full rounded-md bg-white/5 px-3 py-1.5 text-base text-white outline-1 -outline-offset-1 outline-white/10 placeholder:text-gray-500 focus:outline-2 focus:-outline-offset-2 focus:outline-indigo-500 sm:text-sm/6"
                          />
                        </div>
                      </div>

                      <div class="flex items-center justify-between">
                        <div class="flex gap-3">
                          <div class="flex h-6 shrink-0 items-center">
                            <div class="group grid size-4 grid-cols-1">
                              <input
                                id="remember-me"
                                v-model="rememberMe"
                                name="remember-me"
                                type="checkbox"
                                class="col-start-1 row-start-1 appearance-none rounded-sm border border-white/10 bg-white/5 checked:border-indigo-500 checked:bg-indigo-500 indeterminate:border-indigo-500 indeterminate:bg-indigo-500 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-500 disabled:border-gray-300 disabled:bg-gray-100 disabled:checked:bg-gray-100 forced-colors:appearance-auto"
                              />
                              <svg
                                class="pointer-events-none col-start-1 row-start-1 size-3.5 self-center justify-self-center stroke-white group-has-disabled:stroke-white/25"
                                viewBox="0 0 14 14"
                                fill="none"
                              >
                                <path
                                  class="opacity-0 group-has-checked:opacity-100"
                                  d="M3 8L6 11L11 3.5"
                                  stroke-width="2"
                                  stroke-linecap="round"
                                  stroke-linejoin="round"
                                />
                                <path
                                  class="opacity-0 group-has-indeterminate:opacity-100"
                                  d="M3 7H11"
                                  stroke-width="2"
                                  stroke-linecap="round"
                                  stroke-linejoin="round"
                                />
                              </svg>
                            </div>
                          </div>
                          <label for="remember-me" class="block text-sm/6 text-white">
                            Remember me
                          </label>
                        </div>

                        <div class="text-sm/6">
                          <a href="#" class="font-semibold text-indigo-400 hover:text-indigo-300">
                            Forgot password?
                          </a>
                        </div>
                      </div>

                      <div>
                        <button
                          type="submit"
                          :disabled="loading"
                          class="flex w-full justify-center rounded-md bg-indigo-500 px-3 py-1.5 text-sm/6 font-semibold text-white hover:bg-indigo-400 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-500 disabled:opacity-50 disabled:cursor-not-allowed"
                        >
                          <span v-if="!loading">Sign in</span>
                          <span v-else class="flex items-center">
                            <svg class="animate-spin -ml-1 mr-2 h-4 w-4 text-white" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
                              <circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4"></circle>
                              <path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
                            </svg>
                            Signing in...
                          </span>
                        </button>
                      </div>
                    </form>

                    <div>
                      <div class="mt-10 flex items-center gap-x-6">
                        <div class="w-full flex-1 border-t border-white/10" />
                        <p class="text-sm/6 font-medium text-nowrap text-white">
                          Or continue with
                        </p>
                        <div class="w-full flex-1 border-t border-white/10" />
                      </div>

                      <div class="mt-6 grid grid-cols-2 gap-4">
                        <button
                          type="button"
                          @click="signInWithGoogle"
                          class="flex w-full items-center justify-center gap-3 rounded-md bg-white/10 px-3 py-2 text-sm font-semibold text-white inset-ring inset-ring-white/5 hover:bg-white/20 focus-visible:inset-ring-transparent"
                        >
                          <svg class="h-5 w-5" aria-hidden="true" viewBox="0 0 24 24">
                            <path d="M12.0003 4.75C13.7703 4.75 15.3553 5.36002 16.6053 6.54998L20.0303 3.125C17.9502 1.19 15.2353 0 12.0003 0C7.31028 0 3.25527 2.69 1.28027 6.60998L5.27028 9.70498C6.21525 6.86002 8.87028 4.75 12.0003 4.75Z" fill="#EA4335" />
                            <path d="M23.49 12.275C23.49 11.49 23.415 10.73 23.3 10H12V14.51H18.47C18.18 15.99 17.34 17.25 16.08 18.1L19.945 21.1C22.2 19.01 23.49 15.92 23.49 12.275Z" fill="#4285F4" />
                            <path d="M5.26498 14.2949C5.02498 13.5699 4.88501 12.7999 4.88501 11.9999C4.88501 11.1999 5.01998 10.4299 5.26498 9.7049L1.275 6.60986C0.46 8.22986 0 10.0599 0 11.9999C0 13.9399 0.46 15.7699 1.28 17.3899L5.26498 14.2949Z" fill="#FBBC05" />
                            <path d="M12.0004 24.0001C15.2404 24.0001 17.9654 22.935 19.9454 21.095L16.0804 18.095C15.0054 18.82 13.6204 19.245 12.0004 19.245C8.8704 19.245 6.21537 17.135 5.2654 14.29L1.27539 17.385C3.25539 21.31 7.3104 24.0001 12.0004 24.0001Z" fill="#34A853" />
                          </svg>
                          <span class="text-sm/6 font-semibold">Google</span>
                        </button>

                        <button
                          type="button"
                          @click="signInWithGitHub"
                          class="flex w-full items-center justify-center gap-3 rounded-md bg-white/10 px-3 py-2 text-sm font-semibold text-white inset-ring inset-ring-white/5 hover:bg-white/20 focus-visible:inset-ring-transparent"
                        >
                          <svg class="size-5 fill-white" aria-hidden="true" fill="currentColor" viewBox="0 0 20 20">
                            <path
                              fill-rule="evenodd"
                              d="M10 0C4.477 0 0 4.484 0 10.017c0 4.425 2.865 8.18 6.839 9.504.5.092.682-.217.682-.483 0-.237-.008-.868-.013-1.703-2.782.605-3.369-1.343-3.369-1.343-.454-1.158-1.11-1.466-1.11-1.466-.908-.62.069-.608.069-.608 1.003.07 1.531 1.032 1.531 1.032.892 1.53 2.341 1.088 2.91.832.092-.647.35-1.088.636-1.338-2.22-.253-4.555-1.113-4.555-4.951 0-1.093.39-1.988 1.029-2.688-.103-.253-.446-1.272.098-2.65 0 0 .84-.27 2.75 1.026A9.564 9.564 0 0110 4.844c.85.004 1.705.115 2.504.337 1.909-1.296 2.747-1.027 2.747-1.027.546 1.379.203 2.398.1 2.651.64.7 1.028 1.595 1.028 2.688 0 3.848-2.339 4.695-4.566 4.942.359.31.678.921.678 1.856 0 1.338-.012 2.419-.012 2.747 0 .268.18.58.688.482A10.019 10.019 0 0020 10.017C20 4.484 15.522 0 10 0z"
                              clip-rule="evenodd"
                            />
                          </svg>
                          <span class="text-sm/6 font-semibold">GitHub</span>
                        </button>
                      </div>
                    </div>
                  </div>

                  <p class="mt-10 text-center text-sm/6 text-gray-400">
                    Not a member?
                    {{ " " }}
                    <button
                      type="button"
                      @click="$emit('switch-to-signup')"
                      class="font-semibold text-indigo-400 hover:text-indigo-300"
                    >
                      Start a 14 day free trial
                    </button>
                  </p>
                </div>
              </div>
            </DialogPanel>
          </TransitionChild>
        </div>
      </div>
    </Dialog>
  </TransitionRoot>
</template>

<script setup lang="ts">
import { ref } from 'vue'
import { Dialog, DialogPanel, TransitionChild, TransitionRoot } from '@headlessui/vue'
import { XMarkIcon } from '@heroicons/vue/24/outline'

defineProps<{
  open: boolean
}>()

defineEmits<{
  close: []
  'switch-to-signup': []
}>()

const email = ref('')
const password = ref('')
const rememberMe = ref(false)
const loading = ref(false)

const handleSubmit = async () => {
  loading.value = true
  
  try {
    await new Promise(resolve => setTimeout(resolve, 1000))
    console.log('Login attempt:', { email: email.value, rememberMe: rememberMe.value })
    // TODO: Implement actual email/password authentication
    alert('Email/password login not implemented yet. Please use GitHub OAuth.')
  } catch (error) {
    console.error('Login error:', error)
  } finally {
    loading.value = false
  }
}

const signInWithGoogle = () => {
  console.log('Google sign in')
  alert('Google OAuth would be implemented here')
}

const signInWithGitHub = () => {
  console.log('GitHub sign in')
  alert('OAuth implementation removed. Backend now only has basic API endpoint.')
}
</script>

// svelte-front/src/lib/components/AuthModal.svelte
<script lang="ts">
	import { auth } from '$lib/stores/auth';

	let { open = false, onClose } = $props();

	let email = '';
	let password = '';
	let rememberMe = false;
	let loading = false;

	function handleClose() {
		onClose?.();
	}

	function handleOverlayClick(e: MouseEvent) {
		if (e.target === e.currentTarget) {
			handleClose();
		}
	}

	async function handleSubmit(e: Event) {
		e.preventDefault();
		loading = true;
		
		try {
			await new Promise(resolve => setTimeout(resolve, 1000));
			console.log('Login attempt:', { email, rememberMe });
			// TODO: Implement actual email/password authentication
			alert('Email/password login not implemented yet. Please use GitHub OAuth.');
		} catch (error) {
			console.error('Login error:', error);
		} finally {
			loading = false;
		}
	}

	function signInWithGoogle() {
		console.log('Google sign in');
		alert('Google OAuth would be implemented here');
	}

	function signInWithGitHub() {
		console.log('GitHub sign in');
		auth.login();
		handleClose();
	}

	function handleSwitchToSignup() {
		console.log('Switch to signup');
		handleClose();
	}
</script>

{#if open}
	<!-- Modal backdrop -->
	<div 
		class="fixed inset-0 z-50 overflow-y-auto" 
		aria-labelledby="modal-title" 
		role="dialog" 
		aria-modal="true"
	>
		<!-- Background overlay -->
		<div 
			class="fixed inset-0 bg-black/20 backdrop-blur-md transition-opacity" 
			on:click={handleOverlayClick}
			on:keydown={(e) => e.key === 'Escape' && handleClose()}
		></div>

		<!-- Modal container -->
		<div class="flex min-h-full items-end justify-center p-4 text-center sm:items-center sm:p-0">
			<!-- Modal panel -->
			<div class="relative transform overflow-hidden bg-gray-900 px-4 pb-4 pt-5 text-left shadow-xl transition-all sm:my-8 sm:w-full sm:max-w-lg sm:p-0">
				<!-- Close button -->
				<div class="absolute right-0 top-0 pr-4 pt-4">
					<button
						type="button"
						class="rounded-md bg-gray-900 text-gray-400 hover:text-white focus:outline-none focus:ring-2 focus:ring-indigo-500"
						on:click={handleClose}
					>
						<span class="sr-only">Close</span>
						<svg class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
							<path stroke-linecap="round" stroke-linejoin="round" d="M6 18L18 6M6 6l12 12" />
						</svg>
					</button>
				</div>

				<!-- Login form content -->
				<div class="flex min-h-full flex-1 flex-col justify-center py-12 sm:px-6 lg:px-8">
					<div class="sm:mx-auto sm:w-full sm:max-w-md">
						<div class="h-10 w-auto text-indigo-400 font-bold text-2xl text-center">
							LinkShort
						</div>
						<h2 class="mt-6 text-center text-2xl/9 font-bold tracking-tight text-white">
							Sign in to your account
						</h2>
					</div>

					<div class="mt-10 sm:mx-auto sm:w-full sm:max-w-[480px]">
						<div class="bg-gray-800/50 px-6 py-12 outline -outline-offset-1 outline-white/10 sm:rounded-lg sm:px-12">
							<form class="space-y-6" on:submit={handleSubmit}>
								<div>
									<label for="email" class="block text-sm/6 font-medium text-white">
										Email address
									</label>
									<div class="mt-2">
										<input
											id="email"
											bind:value={email}
											type="email"
											name="email"
											autocomplete="email"
											required
											class="block w-full rounded-md bg-white/5 px-3 py-1.5 text-base text-white outline-1 -outline-offset-1 outline-white/10 placeholder:text-gray-500 focus:outline-2 focus:-outline-offset-2 focus:outline-indigo-500 sm:text-sm/6"
										/>
									</div>
								</div>

								<div>
									<label for="password" class="block text-sm/6 font-medium text-white">
										Password
									</label>
									<div class="mt-2">
										<input
											id="password"
											bind:value={password}
											type="password"
											name="password"
											autocomplete="current-password"
											required
											class="block w-full rounded-md bg-white/5 px-3 py-1.5 text-base text-white outline-1 -outline-offset-1 outline-white/10 placeholder:text-gray-500 focus:outline-2 focus:-outline-offset-2 focus:outline-indigo-500 sm:text-sm/6"
										/>
									</div>
								</div>

								<div class="flex items-center justify-between">
									<div class="flex gap-3">
										<div class="flex h-6 shrink-0 items-center">
											<div class="group grid size-4 grid-cols-1">
												<input
													id="remember-me"
													bind:checked={rememberMe}
													name="remember-me"
													type="checkbox"
													class="col-start-1 row-start-1 appearance-none rounded-sm border border-white/10 bg-white/5 checked:border-indigo-500 checked:bg-indigo-500 indeterminate:border-indigo-500 indeterminate:bg-indigo-500 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-500 disabled:border-gray-300 disabled:bg-gray-100 disabled:checked:bg-gray-100 forced-colors:appearance-auto"
												/>
												<svg
													class="pointer-events-none col-start-1 row-start-1 size-3.5 self-center justify-self-center stroke-white group-has-disabled:stroke-white/25"
													viewBox="0 0 14 14"
													fill="none"
												>
													<path
														class="opacity-0 group-has-checked:opacity-100"
														d="M3 8L6 11L11 3.5"
														stroke-width="2"
														stroke-linecap="round"
														stroke-linejoin="round"
													/>
													<path
														class="opacity-0 group-has-indeterminate:opacity-100"
														d="M3 7H11"
														stroke-width="2"
														stroke-linecap="round"
														stroke-linejoin="round"
													/>
												</svg>
											</div>
										</div>
										<label for="remember-me" class="block text-sm/6 text-white">
											Remember me
										</label>
									</div>

									<div class="text-sm/6">
										<a href="#" class="font-semibold text-indigo-400 hover:text-indigo-300">
											Forgot password?
										</a>
									</div>
								</div>

								<div>
									<button
										type="submit"
										disabled={loading}
										class="flex w-full justify-center rounded-md bg-indigo-500 px-3 py-1.5 text-sm/6 font-semibold text-white hover:bg-indigo-400 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-500 disabled:opacity-50 disabled:cursor-not-allowed"
									>
										{#if !loading}
											<span>Sign in</span>
										{:else}
											<span class="flex items-center">
												<svg class="animate-spin -ml-1 mr-2 h-4 w-4 text-white" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
													<circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4"></circle>
													<path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
												</svg>
												Signing in...
											</span>
										{/if}
									</button>
								</div>
							</form>

							<div>
								<div class="mt-10 flex items-center gap-x-6">
									<div class="w-full flex-1 border-t border-white/10" />
									<p class="text-sm/6 font-medium text-nowrap text-white">
										Or continue with
									</p>
									<div class="w-full flex-1 border-t border-white/10" />
								</div>

								<div class="mt-6 grid grid-cols-2 gap-4">
									<button
										type="button"
										on:click={signInWithGoogle}
										class="flex w-full items-center justify-center gap-3 rounded-md bg-white/10 px-3 py-2 text-sm font-semibold text-white inset-ring inset-ring-white/5 hover:bg-white/20 focus-visible:inset-ring-transparent"
									>
										<svg class="h-5 w-5" aria-hidden="true" viewBox="0 0 24 24">
											<path d="M12.0003 4.75C13.7703 4.75 15.3553 5.36002 16.6053 6.54998L20.0303 3.125C17.9502 1.19 15.2353 0 12.0003 0C7.31028 0 3.25527 2.69 1.28027 6.60998L5.27028 9.70498C6.21525 6.86002 8.87028 4.75 12.0003 4.75Z" fill="#EA4335" />
											<path d="M23.49 12.275C23.49 11.49 23.415 10.73 23.3 10H12V14.51H18.47C18.18 15.99 17.34 17.25 16.08 18.1L19.945 21.1C22.2 19.01 23.49 15.92 23.49 12.275Z" fill="#4285F4" />
											<path d="M5.26498 14.2949C5.02498 13.5699 4.88501 12.7999 4.88501 11.9999C4.88501 11.1999 5.01998 10.4299 5.26498 9.7049L1.275 6.60986C0.46 8.22986 0 10.0599 0 11.9999C0 13.9399 0.46 15.7699 1.28 17.3899L5.26498 14.2949Z" fill="#FBBC05" />
											<path d="M12.0004 24.0001C15.2404 24.0001 17.9654 22.935 19.9454 21.095L16.0804 18.095C15.0054 18.82 13.6204 19.245 12.0004 19.245C8.8704 19.245 6.21537 17.135 5.2654 14.29L1.27539 17.385C3.25539 21.31 7.3104 24.0001 12.0004 24.0001Z" fill="#34A853" />
										</svg>
										<span class="text-sm/6 font-semibold">Google</span>
									</button>

									<button
										type="button"
										on:click={signInWithGitHub}
										class="flex w-full items-center justify-center gap-3 rounded-md bg-white/10 px-3 py-2 text-sm font-semibold text-white inset-ring inset-ring-white/5 hover:bg-white/20 focus-visible:inset-ring-transparent"
									>
										<svg class="size-5 fill-white" aria-hidden="true" fill="currentColor" viewBox="0 0 20 20">
											<path
												fill-rule="evenodd"
												d="M10 0C4.477 0 0 4.484 0 10.017c0 4.425 2.865 8.18 6.839 9.504.5.092.682-.217.682-.483 0-.237-.008-.868-.013-1.703-2.782.605-3.369-1.343-3.369-1.343-.454-1.158-1.11-1.466-1.11-1.466-.908-.62.069-.608.069-.608 1.003.07 1.531 1.032 1.531 1.032.892 1.53 2.341 1.088 2.91.832.092-.647.35-1.088.636-1.338-2.22-.253-4.555-1.113-4.555-4.951 0-1.093.39-1.988 1.029-2.688-.103-.253-.446-1.272.098-2.65 0 0 .84-.27 2.75 1.026A9.564 9.564 0 0110 4.844c.85.004 1.705.115 2.504.337 1.909-1.296 2.747-1.027 2.747-1.027.546 1.379.203 2.398.1 2.651.64.7 1.028 1.595 1.028 2.688 0 3.848-2.339 4.695-4.566 4.942.359.31.678.921.678 1.856 0 1.338-.012 2.419-.012 2.747 0 .268.18.58.688.482A10.019 10.019 0 0020 10.017C20 4.484 15.522 0 10 0z"
												clip-rule="evenodd"
											/>
										</svg>
										<span class="text-sm/6 font-semibold">GitHub</span>
									</button>
								</div>
							</div>
						</div>

						<p class="mt-10 text-center text-sm/6 text-gray-400">
							Not a member?
							{" "}
							<button
								type="button"
								on:click={handleSwitchToSignup}
								class="font-semibold text-indigo-400 hover:text-indigo-300"
							>
								Start a 14 day free trial
							</button>
						</p>
					</div>
				</div>
			</div>
		</div>
	</div>
{/if}
